### ISSUE TITLE
Nerves System Shell adds current working directory $PATH, breaking linux-menuconfig

### ISSUE THREAD

**Issue by mattludwigs** [nerves-project/nerves#389] opened 2019-03-11 20:18 UTC
### Environment

* Elixir version: 1.8.1
* Nerves environment

```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.6.6
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_matt
  Vsn:         1.6.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   target
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     target
  toolchain:  /home/mattludwigs/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.1.0
  system:     /home/mattludwigs/.nerves/artifacts/nerves_system_matt-portable-1.6.2
  app:        /home/mattludwigs/code/smartrent/nerver_system_matt

|nerves_bootstrap| Loadpaths End

```

I am using `asdf` to manage Elixir and Erlang versions and I am on Linux.

```
Nerves:           1.4.0
Nerves Bootstrap: 1.5.0
Elixir:           1.8.1
```

### Current behavior

I run `mix nerves.system.shell` and my `$PATH` gets updated with `asdf` elixir paths, but adds two `::` which resolves to the current working directory, which `make linux-menuconfig` will not work if your current working directory is in your `$PATH` 

There is this error
```
You seem to have the current working directory in your
PATH environment variable. This doesn't work.
support/dependencies/dependencies.mk:21: recipe for target 'dependencies' failed
make[1]: *** [dependencies] Error 1
Makefile:23: recipe for target '_all' failed
make: *** [_all] Error 2
```

### Expected behavior

My Path not to be touched, or at the very least the path update without adding the current working directory via a null path like `::`.

I am willing to help in any way to figure this out. I can update my `$PATH` to remove the `::`s and all works from there.

I am not sure who's actually adding the path, but I figured started the conversation here will at least get more eyes on trying to debug.

**Comment by ConnorRigby** [comment] 2019-03-11 20:21
I'm wondering if `BuildRunner: {nil, []}` has anything to do with it. I'm unable to debug right now, but i do know this worked for me on my machine yesterday. I can help investigate later.

**Comment by mattludwigs** [comment] 2019-03-11 20:24
Yeah this working for me a few weeks ago, on this same system, so I am not sure what changed.

**Comment by ConnorRigby** [comment] 2019-03-12 19:08
This seems to be caused by upgrading `asdf-vm` to [v0.7.0](https://github.com/asdf-vm/asdf/releases/tag/v0.7.0)

**Comment by ConnorRigby** [comment] 2019-03-12 19:46
As a work around for this while investigating a proper fix, if you've upgraded to asdf-vm v0.7.0, you can downgrade to v0.6.3.

```
cd $HOME/.asdf && git fetch --tags && git checkout -f v0.6.3
rm -rf $HOME/.asdf/shims && asdf plugin-list | xargs -n1 asdf reshim
```

**Comment by mobileoverlord** [comment] 2019-03-12 19:54
I was able to use `mix nerves.system.shell` using `asdf` `v0.7.0`, but it appears that the `tty_sl` driver throws an argument error when you try to query the window geometry when using OTP `21.3`

**Comment by ConnorRigby** [comment] 2019-03-12 19:55
@mobileoverlord were you using MacOS?

**Comment by mobileoverlord** [comment] 2019-03-12 19:56
I was using ubuntu 18.04

**Comment by robotmay** [comment] 2019-04-09 16:51
Confirming this also happens for me on Ubuntu with that version of asdf.

**Comment by amalbuquerque** [comment] 2019-04-20 08:44
I was able to reproduce this on Ubuntu 18.04 with `asdf` v0.7.1, downgrading to `v0.6.3` did the trick.

**Comment by mobileoverlord** [comment] 2019-04-26 18:57
This is fixed in https://github.com/nerves-project/nerves/releases/tag/v1.4.3

**Comment by grantovich** [comment] 2019-05-03 18:57
I'm using the release that was intended to fix this issue (1.4.3), in essentially the same environment (Ubuntu 18.10, asdf 0.7.1, Elixir 1.8.1, OTP 21.3.7, nerves_system_br 1.7.1), but get the same "You seem to have the current working directory in your PATH" error preventing me from running most `mix` tasks in my custom system. I just set up Nerves for the first time yesterday, so I don't think it could be that something outdated is still hanging around. I've checked and the working directory is certainly not in my `PATH`, and it also does not contain any double-colons. Should I open a new issue?

**Comment by mobileoverlord** [comment] 2019-05-03 19:27
@grantovich Which mix tasks are you having trouble running?

**Comment by grantovich** [comment] 2019-05-03 19:59
@mobileoverlord The specific one I'm stuck on right now is `mix nerves.artifact`, though I'm not sure which others I should be looking at since even `mix help` fails with the same error. `mix nerves.system.shell` does work, and within that shell I'm able to `make` successfully. I've been following the [customization guide](https://hexdocs.pm/nerves/systems.html#customizing-your-own-nerves-system) starting from `nerves_system_rpi`, but with no actual changes yet (aside from updating the deps versions).

**Comment by mobileoverlord** [comment] 2019-05-03 20:08
@grantovich could you try using `{:nerves, github: "nerves-project/nerves", branch: "sanitize-path", override: true, runtime: false}` and let me know if that fixes it?

**Comment by grantovich** [comment] 2019-05-03 20:20
@mobileoverlord Following that replacement I now get this error on `mix help`. It seems my `PATH` is being passed to a function as a charlist, but it was expecting a String.

```
** (FunctionClauseError) no function clause matching in String.to_charlist/1    
    
    The following arguments were given to String.to_charlist/1:
    
        # 1
        '[contents of my PATH]'
    
    Attempted function clauses (showing 1 out of 1):
    
        def to_charlist(string) when is_binary(string)
    
    (elixir) lib/string.ex:2148: String.to_charlist/1
    (elixir) lib/system.ex:691: anonymous fn/1 in System.validate_env/1
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/system.ex:678: System.cmd_opts/3
    (elixir) lib/system.ex:637: System.cmd/3
    lib/nerves/system/br.ex:63: Nerves.System.BR.make/4
    lib/nerves/artifact.ex:20: Nerves.Artifact.build/2
    lib/mix/tasks/compile.nerves_package.ex:31: Mix.Tasks.Compile.NervesPackage.run/1
```

**Comment by mobileoverlord** [comment] 2019-05-03 20:22
Whoops, pushed that up a little too quickly 😄 Can you `mix deps.update nerves` and try again?

**Comment by grantovich** [comment] 2019-05-03 20:34
That seems to have done the trick, I'm now able to `mix help` without errors and generated an artifact successfully. I'll keep using this branch for now, please let me know if there's any info about my environment that would help!

**Closed** 2019-05-06 13:56 UTC
